version: "3"
services:
  backend:
    build: ./backend
    restart: on-failure:10
    command: bash -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
      - static:/usr/src/app/static_root
      - media:/usr/src/app/media
    environment:
      - MYSQL_DB=db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin

  frontend:
    build:
      context: ./frontend
      args:
        - AXIOS_BASEURL=http://backend:8000/api
        - AXIOS_BROWSER_BASEURL=/api
    expose:
      - "3000:3000"
    command: "npm run dev"
    environment:
      - AXIOS_BASEURL=http://backend:8000/api
      - AXIOS_BROWSER_BASEURL=/api
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules