version: "3.9"
   
services:
  db:
    image: mysql
    volumes:
      - ./data/db:/var/lib/mysql/db
    environment:
      - MYSQL_DB=db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin
  web:
    build: .
    command: bash -c "
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_NAME=db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=admin
    depends_on:
      - db

